tasks:
  - init: |
      docker compose pull
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
  - command: |
      docker compose up -d

vscode:
  extensions:
    - ms-python.python
    - formulahendry.code-runner
    - ms-toolsai.jupyter-keymap
