# Generated by Django 4.0.4 on 2022-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
